#!/bin/bash

date=`date +%Y-%m-%d`

files=`ls`

i=1
for filename in $files
do
	if [[ $filename =~ .+\.rs$ ]]
	then
		#echo $filename
		((i+=1))
	fi
done

new_file=`printf 'learn%03i.rs' $i`

echo $new_file

echo "// $new_file" >> $new_file
echo "// " >> $new_file
echo "// @user: sy.wang" >> $new_file
echo "// @date: $date" >> $new_file
echo "// " >> $new_file
echo "" >> $new_file
echo "" >> $new_file
echo "" >> $new_file

vim + $new_file
