#!/bin/bash

file_name=$1

target="../target"

if [[ ! -d $target ]] 
then
	mkdir $target 
fi

rustc --out-dir $target $file_name
test $? -eq 0 && {
	bin_path="${target}/${file_name%.rs*}"
	$bin_path
}

